[package]
name = "colorlyne"
version = "0.1.0"
authors = ["0xadd1e"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colorful = "0.2"
failure = "0.1"
libgit2-sys = "0.8"
libc = "0.2"
